paths:
  /api/producs:
    get:
      summary: Returns a list of products.
      tags:
        - Products
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of products
          # content:
          #   application/json:
          #     schema: 
          #       type: array
          #       items: 
          #         type: string
        '404':    # status code
          description: Error
          # content:
          #   application/json:
          #     schema: 
          #       type: array
          #       items: 
          #         type: string
    post:
      summary: Graba un Producto.
      tags:
        - Products
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON product
          # content:
          #   application/json:
          #     schema: 
          #       type: array
          #       items: 
          #         type: string
        '404':    # status code
          description: Error
          # content:
          #   application/json:
          #     schema: 
          #       type: array
          #       items: 
          #         type: string