paths:
  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Retorna un producto.
      description: Retorna el producto al cual correspone el PID.
      parameters:
        - name: pid
          in: path
          required: true
          description: id del producto que se está solicitando
      responses:
        '200':    # status code
          description: El producto fue obtenido correctamente.
          content:
            application/json:
              schema: 
                type: object
                items: 
                  $ref: '#components/schemas/ProductRespuesta'
